services:

  reverse-proxy:
    image: nginx:1.24
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/auth:/var/www/.auth
    init: true
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend

  frontend:
    image: node:20
    volumes:
      - ./frontend:/app
    init: true
    working_dir: /app
    command: sh -c 'npm install && npm run dev'

  backend:
    build: backend
    volumes:
      - ./backend:/app
    init: true
    environment:
      DEBUG: 1